### ISSUE TITLE
群加不了呢？

### ISSUE THREAD

**Issue by SoberChina** [TogetherOS/cicada#43]
![image](https://user-images.githubusercontent.com/10227558/62912625-90f4b100-bdbb-11e9-9eb6-dc9da5aecc95.png)

**Comment by crossoverJie** [comment]
可以加我 QQ 我拉你入群 731756881发自我的iPhone------------------ 原始邮件 ------------------发件人: sober  <notifications@github.com>发送时间: 2019年8月13日 11:14收件人: TogetherOS/cicada <cicada@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[TogetherOS/cicada] 群加不了呢？ (#43)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TogetherOS/cicada/issues/43?email_source=notifications\u0026email_token=ADXVEPDCHNZA3RXXY5A3RV3QEIRLHA5CNFSM4ILGWLF2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HE3JIYQ",
"url": "https://github.com/TogetherOS/cicada/issues/43?email_source=notifications\u0026email_token=ADXVEPDCHNZA3RXXY5A3RV3QEIRLHA5CNFSM4ILGWLF2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HE3JIYQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
